import { Sarabun } from "next/font/google";
import "./globals.css"; 
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const sarabun = Sarabun({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Acufi",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { readonly children: React.ReactNode }) {
  return (
    <html lang="en" className={sarabun.className}>
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
